appshot/urls.py
from django.urls import path
from appshot.views import (
    todo_list,
    todo_list_detail,
    todo_list_create,
    todo_list_update,
    todo_list_delete,
    todo_item_create,
    todo_item_update,
)

app_name = "todos"

urlpatterns = [
    path("", todo_list, name="todo_list_list"),
    path("<int:id>/", todo_list_detail, name="todo_list_detail"),
    path("create/", todo_list_create, name="todo_list_create"),
    path("<int:id>/edit/", todo_list_update, name="todo_list_update"),
    path("<int:id>/delete/", todo_list_delete, name="todo_list_delete"),
    path("items/create/", todo_item_create, name="todo_item_create"),
    path("items/<int:id>/edit/", todo_item_update, name="todo_item_update"),
]

oneshot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from appshot.views import TodoList


def redirect_to_todo_list_detail(request):
    first_todo_list = TodoList.objects.first()
    if first_todo_list:
        return redirect("todos:todo_list_detail", id=first_todo_list.id)
    else:
        # Handle the case when no TodoList exists
        return redirect("todos:todo_list_list")


urlpatterns = [
    path("", redirect_to_todo_list_detail, name="todo_list_detail"),
    path("admin/", admin.site.urls),
    path("todos/", include(("appshot.urls", "todos"), namespace="todos")),
]

appshot/models.py
from django.db import models


# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(
        null=True,
        blank=True,
    )
    is_completed = models.BooleanField(default=False, null=True)
    list = models.ForeignKey(
        TodoList, related_name="items", on_delete=models.CASCADE
    )

appshot/forms.py
from django.forms import ModelForm
from appshot.models import TodoList, TodoItem


class TodoListForm(ModelForm):
    class Meta:
        model = TodoList
        fields = ("name",)


class TodoItemForm(ModelForm):
    class Meta:
        model = TodoItem
        fields = ("task", "due_date", "is_completed", "list")

appshot/views.py
from django.shortcuts import render, redirect, get_object_or_404
from appshot.models import TodoList, TodoItem
from appshot.forms import TodoListForm, TodoItemForm

# Create your views here.


def todo_list(request):
    todo_lists = TodoList.objects.all()
    context = {"todo_lists": todo_lists}
    return render(request, "todos/todos.html", context)


def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    tasks = todo_list.items.all()
    context = {"todo_list": todo_list, "tasks": tasks}
    return render(request, "todos/todo_list_detail.html", context)


def todo_list_create(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_list")
    else:
        form = TodoListForm()
        context = {"form": form}
        return render(request, "todos/todo_list_create.html", context)


def todo_list_update(request, id):
    post = get_object_or_404(TodoList, id=id)
    if request.method == "POST":
        form = TodoListForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_detail", id=id)
    else:
        form = TodoListForm(instance=post)
    context = {"post_object": post, "form": form}
    return render(request, "todos/todo_list_update.html", context)


def todo_list_delete(request, id):
    post = get_object_or_404(TodoList, id=id)
    if request.method == "POST":
        post.delete()
        return redirect("todos:todo_list_list")

    context = {"post_object": post}
    return render(request, "todos/todo_list_delete.html", context)


def todo_item_create(request):
    if request.method == "POST":
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_list")
        else:
            print("Form is not valid:", form.errors)
    else:
        form = TodoItemForm()

    todo_lists = TodoList.objects.all()
    context = {"form": form, "todo_lists": todo_lists}
    return render(request, "todos/todo_item_create.html", context)


def todo_item_update(request, id):
    todo_item = get_object_or_404(TodoItem, id=id)
    if request.method == "POST":
        form = TodoItemForm(request.POST, instance=todo_item)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_detail", id=todo_item.list.id)
    else:
        form = TodoItemForm(instance=todo_item)

    todo_lists = TodoList.objects.all()
    context = {"todo_lists": todo_lists, "form": form}
    return render(request, "todos/todo_item_update.html", context)

appshot/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    {% block content %}{% endblock content %}
</body>

</html>

appshot/templates/todos/todo_item_create.html
{% extends 'base.html' %}

{% block title %}
Create Todo Item
{% endblock title %}

{% block content %}
<main>
    <div>
        <h1>Create a new Item</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value="Submit">
        </form>
    </div>
</main>
{% endblock content %}

appshot/templates/todos/todo_item_update.html
{% extends 'base.html' %}

{% block title %}
Todo Lists
{% endblock title %}

{% block content %}
<main>
    <div>
        <h1>Update Item</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
    </form>
</main>
{% endblock content %}

appshot/templates/todos/todo_list_create.html
{% extends 'base.html' %}

{% block title %}
Todo Lists
{% endblock title %}

{% block content %}
<main>
    <div>
        <h1>Create a new list</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
    </form>
</main>
{% endblock content %}

appshot/templates/todos/todo_list_delete.html
{% extends 'base.html' %}

{% block title %}
Todo Lists
{% endblock title %}

{% block content %}
<main>
    <div>
        <h1>Are you sure?</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <button>Delete</button>
    </form>
</main>
{% endblock content %}

appshot/templates/todos/todo_list_detail.html
{% extends 'base.html' %}

{% block title %}
Todo Lists
{% endblock title %}

{% block content %}
<main>
    <div>
        <h1>{{todo_list.name}}</h1>
        <p><a href="{% url 'todos:todo_list_update' id=todo_list.id %}">Edit</a></p>
        <p><a href="{% url 'todos:todo_list_delete' id=todo_list.id %}">Delete</a></p>
        <h2>Tasks</h2>
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr>
                    <td><a href="{% url 'todos:todo_item_update' id=task.id %}">{{task.task}}</a></td>
                    <td>{{task.due_date}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}

appshot/templates/todos/todo_list_update.html
{% extends 'base.html' %}

{% block title %}
Todo Lists
{% endblock title %}

{% block content %}
<main>
    <div>
        <h1>Update list</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Update</button>
    </form>
</main>
{% endblock content %}

appshot/templates/todos/todos.html
{% extends 'base.html' %}

{% block title %}
Todo Lists
{% endblock title %}

{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
        <p><a href="{% url 'todos:todo_list_create' %}">Create a new list</a></p>
        <p><a href="{% url 'todos:todo_item_create' %}">Create a new item</a></p>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Items</th>
                </tr>
            </thead>
            <tbody>
                {% for todo_list in todo_lists %}
                <tr>
                    <td>
                        <a href="{% url 'todos:todo_list_detail' id=todo_list.id %}">{{ todo_list.name }}
                        </a>
                    </td>
                    <td>{{ todo_list.items.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}